services:
  database:
    image: postgres:13.9
    restart: unless-stopped
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: tasky
      POSTGRES_USER: tasky
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=tasky
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  administration:
    depends_on:
      - database
      - rabbitmq
    build:
      context: ./services/administration-service
      dockerfile: Dockerfile
    volumes:
      - ./services/administration-service/src:/app/src
    ports:
      - 2602:2602
    environment:
      PORT: 2602
      DATABASE_URL: postgres://tasky:password@database:5432/tasky
      RABBITMQ_URL: amqp://tasky:password@rabbitmq:5672
      JWT_SECRET: secret

  tasks:
    depends_on:
      - rabbitmq
    build:
      context: ./services/tasks-service
      dockerfile: Dockerfile
    environment:
      RABBITMQ_URL: amqp://tasky:password@rabbitmq:5672

volumes:
  postgres-data: null
  rabbitmq_data: null
